[tool.django-stubs]
django_settings_module = "django_models.settings"

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.mypy.plugins.django-stubs]
django_settings_module = "django_models.settings"